import AppKit
import DictationCore

/// A full copy of a pasteboard: every item, every type, in the original order.
public struct PasteboardSnapshot: Equatable {
    public struct Entry: Equatable {
        public var type: NSPasteboard.PasteboardType
        public var data: Data
    }

    public var items: [[Entry]]

    /// Copies every representation, or returns `nil` if any of them cannot be read
    /// (for example data promised by an app that has quit). A partial copy would lose
    /// that representation on restore, so callers must not overwrite the clipboard then.
    @MainActor
    public static func capture(_ pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        guard let pasteboardItems = pasteboard.pasteboardItems else {
            return (pasteboard.types ?? []).isEmpty ? PasteboardSnapshot(items: []) : nil
        }
        var items: [[Entry]] = []
        for item in pasteboardItems {
            var entries: [Entry] = []
            for type in item.types {
                guard let data = item.data(forType: type) else { return nil }
                entries.append(Entry(type: type, data: data))
            }
            items.append(entries)
        }
        return PasteboardSnapshot(items: items)
    }

    @MainActor
    public func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        let restored = items.compactMap { entries -> NSPasteboardItem? in
            guard !entries.isEmpty else { return nil }
            let item = NSPasteboardItem()
            for entry in entries {
                item.setData(entry.data, forType: entry.type)
            }
            return item
        }
        if !restored.isEmpty {
            pasteboard.writeObjects(restored)
        }
    }
}

/// Hands out the transcript only when some app asks for it, so the inserter can tell
/// that the paste was actually read. AppKit may call it on any thread.
final class TranscriptProvider: NSObject, NSPasteboardItemDataProvider, @unchecked Sendable {
    private let text: String
    private let lock = NSLock()
    private var firstRead: TimeInterval?

    init(text: String) {
        self.text = text
    }

    /// System uptime of the first read, or `nil` if nobody has read the text yet.
    var firstReadUptime: TimeInterval? {
        lock.withLock { firstRead }
    }

    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        lock.withLock {
            if firstRead == nil { firstRead = ProcessInfo.processInfo.systemUptime }
        }
        item.setString(text, forType: type)
    }
}

/// Writes text that is only on the clipboard for a moment. The markers from
/// http://nspasteboard.org ask clipboard managers not to record it.
public enum TransientPasteboardWriter {
    public static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    public static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// Declares the text through `provider` (supplied on demand) plus the transient markers.
    /// Returns the pasteboard change count right after the write.
    @MainActor
    @discardableResult
    static func write(_ provider: TranscriptProvider, to pasteboard: NSPasteboard, source: String) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setDataProvider(provider, forTypes: [.string])
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        item.setString(source, forType: sourceType)
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }
}

/// The explicit "copy" button: replaces the clipboard because the user asked for it.
@MainActor
public final class SystemClipboardWriter: ClipboardWriting {
    private let pasteboard: NSPasteboard

    public init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    public func copy(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }
}
